from contextlib import asynccontextmanager
from io import BytesIO
from pathlib import Path
from typing import Annotated

from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.responses import FileResponse, StreamingResponse
from fastapi.staticfiles import StaticFiles

from .models import PlanPdfRequest, RankRequest, TravelRequest
from .services import build_trip_plan, compose_answer, detect_intent, get_memories, initialize_db, retrieve, score_candidate, store_memory

ALLOWED_MEDIA = {"image": {"image/jpeg", "image/png", "image/webp"}, "audio": {"audio/mpeg", "audio/wav", "audio/x-wav", "audio/mp4"}, "video": {"video/mp4", "video/webm"}}


@asynccontextmanager
async def lifespan(_: FastAPI):
    initialize_db()
    yield


app = FastAPI(title="TripPilot AI", version="0.1.0", lifespan=lifespan)
STATIC_DIR = Path(__file__).resolve().parent / "static"
app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")


@app.get("/", include_in_schema=False)
def dashboard():
    return FileResponse(STATIC_DIR / "index.html")


@app.get("/health")
def health():
    return {"status": "ok", "service": "TripPilot AI"}


@app.post("/v1/travel/query")
def travel_query(request: TravelRequest):
    intent, intent_confidence = detect_intent(request.text)
    memories = get_memories(request.user_id)
    conversation = " ".join([request.text, *memories])
    context = retrieve(f"{conversation} {request.detected_landmark or ''}")
    answer = compose_answer(request.text, intent, request.detected_landmark, context, memories, request.profile)
    final_plan = build_trip_plan(conversation, context)
    ready_to_download = final_plan is not None
    if final_plan:
        intent = "itinerary_generation"
        answer, plan_context = final_plan
    else:
        plan_context = [f"{item['topic']}: {item['content']}" for item in context]
    confidence = round(min(.95, (.65 * intent_confidence) + (.10 * bool(context)) + (.15 * bool(request.detected_landmark)) + (.10 * bool(request.text))), 2)
    store_memory(request.user_id, "session", request.text)
    store_memory(request.user_id, "response", answer)
    return {"answer": answer, "intent": intent, "confidence": confidence, "requires_clarification": confidence < .60, "ready_to_download": ready_to_download, "plan_context": plan_context, "retrieved_context": context, "memory_used": len(memories)}


@app.post("/v1/decision/rank")
def rank_options(request: RankRequest):
    ranked = sorted((score_candidate(candidate) for candidate in request.candidates), key=lambda item: item["score"], reverse=True)
    return {"recommendation": ranked[0], "ranked_options": ranked, "formula": "30% price + 25% location + 20% rating + 15% preference + 10% amenities"}


@app.post("/v1/plan/pdf")
def download_plan(request: PlanPdfRequest):
    """Create a lightweight, printable travel brief from the active AI result."""
    from reportlab.lib.colors import HexColor
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=.7 * inch, leftMargin=.7 * inch, topMargin=.65 * inch, bottomMargin=.65 * inch)
    styles = getSampleStyleSheet()
    title = ParagraphStyle("TripPilotTitle", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=22, leading=27, textColor=HexColor("#172554"), spaceAfter=12)
    body = ParagraphStyle("TripPilotBody", parent=styles["BodyText"], fontName="Helvetica", fontSize=10.5, leading=16, textColor=HexColor("#1e293b"), spaceAfter=9)
    label = ParagraphStyle("TripPilotLabel", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=11, leading=15, textColor=HexColor("#0e7490"), spaceBefore=12, spaceAfter=6)
    escape = lambda text: text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\n", "<br/>")
    story = [Paragraph("TripPilot AI", ParagraphStyle("Brand", parent=label, textColor=HexColor("#2563eb"))), Paragraph(escape(request.title.title()), title), Paragraph("YOUR TRAVEL PLAN", label), Paragraph(escape(request.answer), body)]
    if request.context:
        story.extend([Spacer(1, 4), Paragraph("TRAVEL CONTEXT", label)])
        story.extend(Paragraph(f"• {escape(item)}", body) for item in request.context)
    story.extend([Spacer(1, 14), Paragraph("Generated by TripPilot AI. Verify bookings, entry requirements, and live conditions before travel.", ParagraphStyle("Footer", parent=body, fontSize=8.5, leading=12, textColor=HexColor("#64748b")))])
    doc.build(story)
    buffer.seek(0)
    return StreamingResponse(buffer, media_type="application/pdf", headers={"Content-Disposition": "attachment; filename=trippilot-travel-plan.pdf"})


@app.post("/v1/multimodal/{modality}")
async def upload_media(modality: str, file: Annotated[UploadFile, File(...)]):
    if modality not in ALLOWED_MEDIA:
        raise HTTPException(status_code=404, detail="Supported modalities: image, audio, video")
    if file.content_type not in ALLOWED_MEDIA[modality]:
        raise HTTPException(status_code=415, detail=f"Unsupported {modality} file type")
    content = await file.read()
    if len(content) > 25 * 1024 * 1024:
        raise HTTPException(status_code=413, detail="Maximum upload size is 25 MB")
    # Production adapters should send the in-memory bytes to a vision/STT/video API,
    # then discard them. This MVP intentionally never persists uploaded media.
    return {"modality": modality, "filename": file.filename, "bytes_processed": len(content), "status": "accepted", "next_step": f"Configure a {modality} provider adapter to analyze this upload."}
